<?php
 require_once(dirname(__FILE__).'/main.php'); define('LOGFILE1', 'act_step_logs.log'); define('LOGFILE2', 'act_extra_logs.log'); define('ACTOKTIME', 3600*2); class logs extends main { function db_add_step_mail_log( $data, $user_id ) { $now = $this->get_now_date(); try { $sql = "INSERT INTO `step_mail_logs`
					(`group_id`, `step_mail_id`, `title`, `contents`, `story_no`, `send_date`, `user_id`, `send_flg`, `created` ) 
					VALUES ( :group_id, :step_mail_id, :title, :contents, :story_no, :send_date, :user_id, :send_flg, :created )"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':group_id', $data['group_id'] ); $this->stmt->bindValue( ':step_mail_id', $data['id'] ); $this->stmt->bindValue( ':title', $data['title'] ); $this->stmt->bindValue( ':contents', $data['contents'] ); $this->stmt->bindValue( ':story_no', $data['story_no'] ); $this->stmt->bindValue( ':send_date', $data['send_date'] ); $this->stmt->bindValue( ':user_id', $user_id ); $this->stmt->bindValue( ':send_flg', $data['send_flg'] ); $this->stmt->bindValue( ':created', $now ); $this->stmt->execute(); } catch( PDOException $e ){ die( $e->getMessage() ); } } function db_update_step_mail_log( $data, $id ) { $now = $this->get_now_date(); try { $sql = 'UPDATE `step_mail_logs`
					SET `send_date`=:send_date,`send_flg`=:send_flg, `modified`=:modified
		    		WHERE `id` = :id'; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':send_date', $data['send_date'] ); $this->stmt->bindValue( ':send_flg', $data['send_flg'] ); $this->stmt->bindValue( ':modified', $now ); $this->stmt->bindValue( ':id', $id ); $this->stmt->execute(); } catch( PDOException $e ){ die( $e->getMessage() ); } } function db_delete_flg_step_log( $term ) { try { $sql = 'UPDATE `step_mail_logs`
					SET `deleted`=NOW()
					WHERE TO_DAYS(NOW()) - TO_DAYS(`created`) >= :term
					AND `deleted` IS NULL'; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':term', $term ); $this->stmt->execute(); } catch( PDOException $e ){ die( $e->getMessage() ); } } function db_delete_flg_extra_log( $term ) { try { $sql = 'UPDATE `extra_mail_logs`
					SET `deleted`=NOW()
					WHERE TO_DAYS(NOW()) - TO_DAYS(`created`) >= :term
					AND `deleted` IS NULL'; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':term', $term ); $this->stmt->execute(); } catch( PDOException $e ){ die( $e->getMessage() ); } } function db_delete_step_log( $term ) { try { $sql = 'DELETE FROM step_mail_logs
					WHERE TO_DAYS(NOW()) - TO_DAYS(`created`) >= :term
					AND `send_flg` !=99'; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':term', $term ); $this->stmt->execute(); } catch( PDOException $e ){ die( $e->getMessage() ); } } function db_delete_extra_log_id( $id ) { try { $sql = "DELETE FROM extra_mail_logs
			WHERE `send_flg` = 0
			AND `extra_mail_id` = :id"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':id', $id, PDO::PARAM_INT ); $this->stmt->execute(); } catch( PDOException $e ){ die( $e->getMessage() ); } } function db_delete_extra_log( $term ) { try { $sql = 'DELETE FROM extra_mail_logs
					WHERE TO_DAYS(NOW()) - TO_DAYS(`created`) >= :term
					AND `send_flg` !=99'; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':term', $term ); $this->stmt->execute(); } catch( PDOException $e ){ die( $e->getMessage() ); } } function count_all_step_mail_log() { $result = FALSE; $this->db_count_all_step_mail_log(); $row = $this->stmt->fetchAll(); $cnt = count( $row ); if($cnt >= 1) { $result = $cnt; } return $result; } private function db_count_all_step_mail_log() { try { $sql = "SELECT COUNT(sl.id) FROM step_mail_logs AS sl LEFT JOIN users AS u ON sl.user_id = u.id
					WHERE sl.deleted IS NULL
					GROUP BY sl.`step_mail_id`, sl.`group_id`"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function get_all_step_mail_log( &$data, $start=0, $num=999 ) { $result = FALSE; $this->db_all_step_mail_log( $start, $num ); $row = $this->stmt->fetchAll(); $cnt = count( $row ); if($cnt >= 1) { $data = $row; $result = TRUE; } return $result; } private function db_all_step_mail_log( $start, $num ) { try { $sql = "SELECT  sl.id, sl.group_id, sl.step_mail_id, sl.story_no, sl.title, sl.send_date, sl.send_flg
					FROM step_mail_logs AS sl LEFT JOIN users AS u ON sl.user_id = u.id
					WHERE sl.deleted IS NULL
					GROUP BY sl.`step_mail_id`, sl.`group_id`
					ORDER BY `send_date` DESC 
					LIMIT :start, :num"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':start', $start, PDO::PARAM_INT ); $this->stmt->bindValue( ':num', $num, PDO::PARAM_INT ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function get_step_mail_log( $id, &$data ) { $result = false; $this->db_step_mail_log( $id ); $row = $this->stmt->fetchAll(); $cnt = count( $row ); if($cnt == 1) { $data = $row[0]; $result = true; } return $result; } private function db_step_mail_log( $id ) { try { $sql = "SELECT TA.*, TB.`email`
					FROM `step_mail_logs` AS TA LEFT JOIN `users` AS TB ON TA.`user_id` = TB.`id`
					WHERE TA.`id` = :id"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':id', $id, PDO::PARAM_INT ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function is_user_mail_logs( $user_id, $step_mail_id ) { $result = false; try { $sql = "SELECT COUNT(`id`) as cnt FROM `step_mail_logs`
			WHERE `user_id` = :user_id
			AND `step_mail_id` = :step_mail_id
			AND (`send_flg` = 1 OR `send_flg` = 99)"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':user_id', $user_id, PDO::PARAM_INT ); $this->stmt->bindValue( ':step_mail_id', $step_mail_id, PDO::PARAM_INT ); $this->stmt->execute(); $row = $this->stmt->fetchAll(); $count = $row[0]['cnt']; if($count == 0) { $result = true; } return $result; } catch( PDOException $e ){ die( $e->getMessage() ); } } function make_page_link( $search, $cur_page, $num_pages, $disp=8 ) { $search_link = URL.'/admin/logs/?'; $search_arr[] = 'status='.$search["status"]; $search_link .= implode( '&', $search_arr ); $page_links = ''; $next = $cur_page+1; $prev = $cur_page-1; $start = ($cur_page-floor($disp/2) > 0) ? ($cur_page-floor($disp/2)) : 1; $end = ($start > 1) ? ($cur_page+floor($disp/2)) : $disp; if($cur_page > 1 ) { $page_links .= '<li><a href="'.$search_link.'&page='.$prev.'">&laquo; 前へ</a></li>'; } if($start >= 1){ $class = ($cur_page == 1) ? ' class="active"' : '' ; $page_links .= '<li'.$class.'><a href="'.$search_link.'&page=1">1</a></li>'; if($start > floor($disp/2)) $page_links .= '<li><a href="#">...</a></li>'; } for( $i=$start; $i<=$end; $i++ ) { $class = ($cur_page == $i) ? ' class="active"' : '' ; if($i <= $num_pages && $i > 1 ) { $page_links .= '<li'.$class.'><a href="'.$search_link.'&page='.$i.'">'.$i.'</a></li>'; } } if($num_pages > $end){ if($num_pages-1 > $end ) $page_links .= '<li><a href="#">...</a></li>'; $page_links .= '<li><a href="'.$search_link.'&page='.$num_pages.'">'.$num_pages.'</a></li>'; } if($cur_page < $num_pages){ $page_links .= '<li><a href="'.$search_link.'&page='.$next.'">次へ &raquo;</a></li>'; } return $page_links; } function db_add_extra_mail_log( $data, $user_id ) { try { $sql = "INSERT INTO `extra_mail_logs`(
			`group_id`, `extra_mail_id`, `title`, `contents`, `send_date`, `user_id`, `send_flg`, `created` )
			VALUES ( :group_id, :extra_mail_id, :title, :contents, :send_date, :user_id, :send_flg, NOW() )"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':group_id', $data['group_id'] ); $this->stmt->bindValue( ':extra_mail_id', $data['id'] ); $this->stmt->bindValue( ':title', $data['title'] ); $this->stmt->bindValue( ':contents', $data['contents'] ); $this->stmt->bindValue( ':send_date', $data['send_date'] ); $this->stmt->bindValue( ':user_id', $user_id ); $this->stmt->bindValue( ':send_flg', $data['send_flg'] ); $this->stmt->execute(); } catch( PDOException $e ){ die( $e->getMessage() ); } } function db_update_extra_mail_log( $data, $id ) { $now = $this->get_now_date(); try { $sql = "UPDATE `extra_mail_logs`
					SET `title`='',`contents`='',`send_date`=:send_date,`send_flg`=:send_flg,`modified`=:modified
		    		WHERE `id` = :id"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':send_date', $data['send_date'] ); $this->stmt->bindValue( ':send_flg', $data['send_flg'] ); $this->stmt->bindValue( ':modified', $now ); $this->stmt->bindValue( ':id', $id ); $this->stmt->execute(); } catch( PDOException $e ){ die( $e->getMessage() ); } } function is_extra_mail_logs_user( $extra_mail_id, $user_id, $send_flg=0 ) { $result = FALSE; try { $sql = "SELECT count(*) cnt
			FROM `extra_mail_logs` 
			WHERE `extra_mail_id` = :extra_mail_id
			AND `user_id` = :user_id
			AND `send_flg` = :send_flg"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':extra_mail_id', $extra_mail_id ); $this->stmt->bindValue( ':user_id', $user_id ); $this->stmt->bindValue( ':send_flg', $send_flg ); $this->stmt->execute(); $row = $this->stmt->fetchAll(); $cnt = $row[0]['cnt']; if($cnt >= 1) { $result = $cnt; } } catch(PDOException $e){ die($e->getMessage()); } return $result; } function db_del_extra_mail_logs_user( $extra_mail_id, $user_id, $send_flg=0 ) { try { $sql = "DELETE
			FROM `extra_mail_logs` 
			WHERE `extra_mail_id` = :extra_mail_id
			AND `user_id` = :user_id
			AND `send_flg` = :send_flg"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':extra_mail_id', $extra_mail_id ); $this->stmt->bindValue( ':user_id', $user_id ); $this->stmt->bindValue( ':send_flg', $send_flg ); $this->stmt->execute(); $row = $this->stmt->fetchAll(); } catch(PDOException $e){ die($e->getMessage()); } } function del_extra_log_user_id( $user_id ) { try { $sql = "DELETE
					FROM extra_mail_logs 
					WHERE 
					user_id = :user_id"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':user_id', $user_id ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function get_all_extra_mail_log( &$data, $start=0, $num=999 ) { $result = FALSE; $this->db_all_extra_mail_log( $start, $num ); $row = $this->stmt->fetchAll(); $cnt = count( $row ); if($cnt >= 1) { $data = $row; $result = TRUE; } return $result; } private function db_all_extra_mail_log( $start, $num ) { try { $sql = "SELECT TA.id, TA.group_id, TA.send_date, TA.send_flg, TA.title
					FROM extra_mail_logs AS TA LEFT JOIN users AS TC ON TA.user_id = TC.id
					GROUP BY TA.`group_id`
					LIMIT :start, :num"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':start', $start, PDO::PARAM_INT ); $this->stmt->bindValue( ':num', $num, PDO::PARAM_INT ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function get_extra_mail_log( $id, &$data ) { $result = false; $this->db_extra_mail_log( $id ); $row = $this->stmt->fetchAll(); $cnt = count( $row ); if($cnt == 1) { $data = $row[0]; $result = true; } return $result; } private function db_extra_mail_log( $id ) { try { $sql = "SELECT TA.*, TB.`email`
					FROM `extra_mail_logs` AS TA LEFT JOIN `users` AS TB ON TA.`user_id` = TB.`id`
					WHERE TA.`id` = :id"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':id', $id, PDO::PARAM_INT ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function get_step_mail_error_count( $user_id, $data ) { $result = false; $this->db_step_mail_error_count( $user_id, $data); $row = $this->stmt->fetchAll(); $count = $row[0][0]; return $count; } private function db_step_mail_error_count( $user_id, $data ) { try { $sql = "SELECT COUNT(*) 
			FROM step_mail_logs 
			WHERE 
			user_id = :user_id
			AND step_mail_id = :step_mail_id 
			AND story_no = :story_no 
			AND send_flg = 0 "; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':user_id', $user_id, PDO::PARAM_INT ); $this->stmt->bindValue( ':step_mail_id', $data['id'], PDO::PARAM_INT ); $this->stmt->bindValue( ':story_no', $data['story_no'], PDO::PARAM_INT ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function db_del_step_mail_logs_errdata( $step_id ) { try { $sql = "DELETE 
			FROM step_mail_logs 
			WHERE 
			step_mail_id = :step_mail_id
			AND send_flg = 0"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':step_mail_id', $step_id ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function is_step_mail_logs_user( $step_mail_id, $user_id, $send_flg=0 ) { $result = FALSE; try { $sql = "SELECT count(id) cnt
			FROM `step_mail_logs` 
			WHERE `step_mail_id` = :step_mail_id
			AND `user_id` = :user_id
			AND `send_flg` = :send_flg"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':step_mail_id', $step_mail_id ); $this->stmt->bindValue( ':user_id', $user_id ); $this->stmt->bindValue( ':send_flg', $send_flg ); $this->stmt->execute(); $row = $this->stmt->fetchAll(); $cnt = $row[0]['cnt']; if($cnt >= 1) { $result = $cnt; } } catch(PDOException $e){ die($e->getMessage()); } return $result; } function db_del_step_mail_logs_user( $step_mail_id, $user_id, $send_flg=0 ) { try { $sql = "DELETE 
			FROM step_mail_logs 
			WHERE step_mail_id = :step_mail_id
			AND user_id = :user_id
			AND send_flg = :send_flg"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':step_mail_id', $step_mail_id ); $this->stmt->bindValue( ':user_id', $user_id ); $this->stmt->bindValue( ':send_flg', $send_flg ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function get_extra_mail_error_count( $user_id, $data ) { $result = false; $this->db_extra_mail_error_count( $user_id, $data); $row = $this->stmt->fetchAll(); $count = $row[0][0]; return $count; } private function db_extra_mail_error_count( $user_id, $data ) { try { $sql = "SELECT COUNT(*) 
			FROM extra_mail_logs 
			WHERE 
			user_id = :user_id
			AND extra_mail_id = :extra_mail_id  
			AND send_flg = 0"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':user_id', $user_id, PDO::PARAM_INT ); $this->stmt->bindValue( ':extra_mail_id', $data['id'], PDO::PARAM_INT ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function db_del_extra_mail_logs_errdata( $extra_id ) { try { $sql = "DELETE 
			FROM extra_mail_logs 
			WHERE 
			extra_mail_id = :extra_mail_id
			AND send_flg = 0"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':extra_mail_id', $extra_id ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function check_extra_mail_log( $id, $flag ) { $result = false; $this->db_check_extra_mail_log( $id, $flag ); $row = $this->stmt->fetchAll(); $count = $row[0][0]; if($count >= 1) { $result = true; } return $result; } private function db_check_extra_mail_log( $id, $flag ) { try { $sql = "SELECT COUNT(*)
			FROM extra_mail_logs 
			WHERE 
			extra_mail_id = :extra_mail_id
			AND send_flg = :send_flg"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':extra_mail_id', $id, PDO::PARAM_INT ); $this->stmt->bindValue( ':send_flg', $flag, PDO::PARAM_INT ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function get_extra_mail_logs_send_done( $id ) { $result = false; $this->db_get_extra_mail_logs_send_done( $id ); $row = $this->stmt->fetchAll(); $cnt = count( $row ); if($cnt == 1) { $result = $row[0]['send_date']; } return $result; } private function db_get_extra_mail_logs_send_done( $id ) { try { $sql = "SELECT MAX(`send_date`) as send_date
			FROM extra_mail_logs 
			WHERE 
			extra_mail_id = :extra_mail_id
			GROUP BY extra_mail_id"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':extra_mail_id', $id, PDO::PARAM_INT ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function check_send_flg( $log, &$count ) { $group_id = $log['group_id']; $step_mail_id = $log['step_mail_id']; $num = 0; $this->db_check_send_flg( $group_id, $step_mail_id, $num ); $row = $this->stmt->fetchAll(); $count['err'] = $row[0][0]; $num = 1; $this->db_check_send_flg( $group_id, $step_mail_id, $num ); $row = $this->stmt->fetchAll(); $count['done'] = $row[0][0]; $num = 99; $this->db_check_send_flg( $group_id, $step_mail_id, $num ); $row = $this->stmt->fetchAll(); $count['on'] = $row[0][0]; } private function db_check_send_flg( $group_id, $step_mail_id, $num ) { try { $sql = "SELECT COUNT(*)
			FROM step_mail_logs 
			WHERE 
			group_id = :group_id
			AND step_mail_id = :step_mail_id
			AND send_flg = :num"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->bindValue( ':group_id', $group_id, PDO::PARAM_INT ); $this->stmt->bindValue( ':step_mail_id', $step_mail_id, PDO::PARAM_INT ); $this->stmt->bindValue( ':num', $num, PDO::PARAM_INT ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function cnt_step_mail_log( $max_cnt ) { $result = false; $this->db_cnt_step_mail_log(); $row = $this->stmt->fetchAll(); $count = $row[0][0]; echo "ログ件数(ステップメール)[" . $count . "]\n"; if($count >= $max_cnt) { $result = true; } return $result; } private function db_cnt_step_mail_log() { try { $sql = "SELECT COUNT(*)
			FROM step_mail_logs"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function db_delete_step_log_cnt( $del_cnt ) { try { $sql = "DELETE FROM step_mail_logs 
		    WHERE `send_flg` != 99 
		    ORDER BY `created` 
		    LIMIT " . $del_cnt; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->execute(); echo $del_cnt . "件のログを削除しました\n"; } catch( PDOException $e ){ die( $e->getMessage() ); } } function cnt_extra_mail_log( $max_cnt ) { $result = false; $this->db_cnt_extra_mail_log(); $row = $this->stmt->fetchAll(); $count = $row[0][0]; echo "ログ件数(号外メール)[" . $count . "]\n"; if($count >= $max_cnt) { $result = true; } return $result; } private function db_cnt_extra_mail_log() { try { $sql = "SELECT COUNT(*)
			FROM extra_mail_logs"; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->execute(); } catch(PDOException $e){ die($e->getMessage()); } } function db_delete_extra_log_cnt( $del_cnt ) { try { $sql = "DELETE FROM extra_mail_logs	WHERE `send_flg` != 99 ORDER BY  `created` LIMIT "; $sql = $sql . $del_cnt; $this->stmt = $this->pdo->prepare( $sql ); $this->stmt->execute(); echo $del_cnt . "件のログを削除しました\n"; } catch( PDOException $e ){ die( $e->getMessage() ); } } function check_act_mail() { $_SESSION['acttime1'] = ''; $_SESSION['acttime2'] = ''; $_SESSION['acterr'] = ''; $_SESSION['actflg'] = ''; $result1 = $this->get_acttime(1); $result2 = $this->get_acttime(2); if ($result1['flg']=='err' || $result2['flg']=='err') { $str = $result1['err'].'<br>'.$result2['err']; $str = ltrim($str, '<br>'); $str = rtrim($str, '<br>'); $_SESSION['acterr'] = $str; $_SESSION['actflg'] = 'err'; } else if ($result1['flg']=='not' || $result2['flg']=='not') { $str = $result1['err'].'<br>'.$result2['err']; $str = ltrim($str, '<br>'); $str = rtrim($str, '<br>'); $_SESSION['acterr'] = $str; $_SESSION['actflg'] = 'not'; } else { $_SESSION['acterr'] = ''; $_SESSION['actflg'] = 'ok'; } $_SESSION['acttime1'] = $result1['time']; $_SESSION['acttime2'] = $result2['time']; } private function get_acttime( $file_no ) { if ($file_no == 1){ $file = LOGFILE1; $type='ステップメール'; }else{ $file = LOGFILE2; $type='号外メール'; } $time = ''; $now_time = microtime(true); $file_path = dirname(__FILE__).'/../admin/mails/'.$file; if (is_readable($file_path)) { $current = file_get_contents($file_path); $time = explode("\n", $current); $get_time = $time['0']; $diff = $now_time - $get_time; if (empty($time['1'])) { if ($diff < ACTOKTIME) { $result['err'] = $type.'の動作を確認中です。'; $result['flg'] = 'not'; $result['time'] = $get_time; } else{ $diff_2_hour = round( $diff/3600, 1 ); $result['err'] = $type.'のcronが正しく動作していない可能性があります。（未稼働時間：'.$diff_2_hour.'時間）'; $result['flg'] = 'err'; $result['time'] = $get_time; } } else { if ($diff < ACTOKTIME) { $result['err'] = ''; $result['flg'] = 'ok'; $result['time'] = $get_time; } else{ $diff_2_hour = round( $diff/3600, 1 ); $result['err'] = $type.'のcronが正しく動作していない可能性があります。（未稼働時間：'.$diff_2_hour.'時間）'; $result['flg'] = 'err'; $result['time'] = $get_time; } } } else{ $this->set_acttime( $file_no ); $result['err'] = $type.'の動作を確認中です。'; $result['flg'] = 'not'; $result['time'] = $now_time; } return $result; } function set_acttime( $file_no ) { if ($file_no == 1){ $file = LOGFILE1; }else{ $file = LOGFILE2; } $file_path = dirname(__FILE__).'/../admin/mails/'.$file; if (is_readable($file_path)) { $current = file_get_contents($file_path); $time = explode("\n", $current); $now_time1 = microtime(true); $now_time2 = $time['0']; $now_time = $now_time1."\n".$now_time2; } else{ $now_time = microtime(true); $now_time = $now_time; } file_put_contents($file_path, $now_time); } } ?>